config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      unlocks: 'users/unlocks',
      passwords: 'user/passwords'
  }

  resources :products do
    collection do
      get :search
      post :search_for_dish
    end
  end

  get "/calculators" => "home#calculators", as: :calculators
  get "/informacje" => "home#info", as: :info
  post "/bmi" => "home#bmi", as: :bmi

  resources :day_diets
  resources :diets
  resources :dishes
  resources :ingredients do
    member do
      get :info
    end
  end

end

app/models/day_diet.rb
class DayDiet < ApplicationRecord
  belongs_to :diet
  belongs_to :user
  has_many :dishes, dependent: :destroy
end

app/controllers/day_diets_controller.rb
class DayDietsController < ApplicationController

  load_and_authorize_resource

  def new
    @new_day_diet = DayDiet.new
    render layout: false
  end

  def create
    puts params.inspect
    puts day_diet_params.inspect
    diet = Diet.find(params[:diet_id])
    @new_day_diet = diet.day_diets.new(day_diet_params)
    @new_day_diet.user_id = current_user.id
    current_user.day_diets.count == 0 ? redirect = diet_path(diet) : redirect = ""
    respond_to do |format|
      if @new_day_diet.save
        format.json { render json: {message: t("activerecord.day_diet.day_diet_created"), day_diet_item: render_to_string(partial: 'day_diet_item', locals: {day_diet: @new_day_diet}).html_safe, location: redirect}, status: :ok }
      else
        format.json { render json: {message: t('errors.messages.errors_occured'), errors: @new_day_diet.errors.messages}, status: :unprocessable_entity }
      end
    end
  end

  def show
    @day_diet = DayDiet.includes(:diet,:dishes).find(params[:id])
    @dishes = @day_diet.dishes
  end

  def destroy
    @day_diet = DayDiet.find(params[:id])

    puts @day_diet
    respond_to do |format|
      if @day_diet.destroy
        format.json { render json: {message: t("global.deleted")}, status: :ok }
      else
        format.json { render json: {message: t('errors.messages.errors_occured')}, status: :unprocessable_entity }
      end
    end
  end

  private

  def day_diet_params
    params.require(:day_diet).permit(:name)
  end

end

app/views/day_diets/_day_diet_item.haml
.col.s12.m6.l4{id: "day-diet#{day_diet.id}"}
  .card.horizontal.hoverable
    .card-stacked
      .card-content
        .center
          %i.fa.fa-calendar.fa-2x
        %p
          = t("activerecord.day_diet.name")
          %span.bold
            = day_diet.name
        %p
          = t("activerecord.day_diet.amount")
          %span.bold
            = day_diet.dishes.count
      .card-action
        = link_to day_diet_path(day_diet), class: "btn waves-effect waves-light" do
          = t("global.show")
          %i.fa.fa-eye
        .btn.deep-orange.darken-4.waves-effect.waves-light.js-destroy-modal{data: {id: day_diet.id}}
          = t("global.delete")
          %i.fa.fa-trash

app/views/day_diets/new.haml
= form_for @new_day_diet, format: :json, html: {id: "js-new-day-diet"} do |f|
  .modal-content
    %i.fa.fa-times.modal-close.right
    .input-field.hide
      = label_tag :diet_id
      = text_field_tag :diet_id
      .error.red-text
    .input-field
      = f.label :name, t("activerecord.day_diet.new_name")
      = f.text_field :name, autofocus: true
      .error.red-text
    .modal-footer
      .actions.input-field
        = f.button t("activerecord.day_diet.create_day_diet"), class: 'btn waves-effect waves-light', type: :submit

app/views/day_diets/show.haml
.row
  .container
    .col.s6.center
      .row
        %h6
          = t("activerecord.diet.name")
      .row
        %h5
          = @day_diet.diet.name
    .col.s6.center
      .row
        %h6
          = t("activerecord.diet.kcal")
      .row
        %h4
          = @day_diet.diet.kcal
    .col.s12.center.row
      %h5
        = @day_diet.name
    #day-diet-id{data: {id: "#{@day_diet.id}"}}

    - if @dishes.present?
      .row
        = link_to t("activerecord.dish.new"), new_dish_path, class: 'btn waves-effect waves-light js-new-dish'
      .row#dish-list
        - @dishes.each do |dish|
          = render partial: 'dishes/dish_item', locals: {dish: dish}
    - else
      .center
        %h5
          = t("activerecord.dish.no_dishes")
        = link_to t("activerecord.dish.new"), new_dish_path, class: 'btn waves-effect waves-light js-new-dish'


#js-destroy-modal.modal.bottom-sheet
  .modal-content.center
    .btn.deep-orange.darken-4.waves-effect.waves-light.js-destroy-dish{data: {id: ''}}
      = t("global.delete")
      %i.fa.fa-trash
  .modal-footer
    .btn.btn-flat.modal-close
      = t("global.close")
      %i.fa.fa-times

#js-new-modal.modal