config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      unlocks: 'users/unlocks',
      passwords: 'user/passwords'
  }

  resources :products do
    collection do
      get :search
      post :search_for_dish
    end
  end

  get "/calculators" => "home#calculators", as: :calculators
  get "/informacje" => "home#info", as: :info
  post "/bmi" => "home#bmi", as: :bmi

  resources :day_diets
  resources :diets
  resources :dishes
  resources :ingredients do
    member do
      get :info
    end
  end

end

app/models/diet.rb
class Diet < ApplicationRecord
  belongs_to :user
  has_many :day_diets, dependent: :destroy

  validates :name, presence: true
  validates :kcal, presence: true
  validates :kcal, numericality: {greater_than: 0}
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController

  load_and_authorize_resource

  before_action :set_user, :index

  def index
    @diets = @user.diets
  end

  def new
    @new_diet = Diet.new
    render layout: false
  end

  def create
    @new_diet = current_user.diets.new(diet_params)
    current_user.diets.count == 0 ? redirect = diets_path : redirect = ""
    respond_to do |format|
      if @new_diet.save
        format.json { render json: {message: t("activerecord.diet.diet_created"), diet_item: render_to_string(partial: 'diet_item', locals: {diet: @new_diet}).html_safe, location: redirect}, status: :ok }
      else
        format.json { render json: {message: t('errors.messages.errors_occured'), errors: @new_diet.errors.messages}, status: :unprocessable_entity }
      end
    end
  end

  def show
    @diet = Diet.find(params[:id])
    @day_diets = @diet.day_diets
  end

  def destroy
    @diet = Diet.find(params[:id])

    respond_to do |format|
      if @diet.destroy
        format.json { render json: {message: t("global.deleted")}, status: :ok }
      else
        format.json { render json: {message: t('errors.messages.errors_occured')}, status: :unprocessable_entity }
      end
    end
  end

  private

  def diet_params
    params.require(:diet).permit(:name, :kcal)
  end

  def set_user
    @user = current_user
  end

end

app/views/diets/_diet_item.haml
%tr{id: "diet#{diet.id}"}
  %td
    = diet.name
  %td
    = diet.kcal
  %td
    = link_to diet_path(diet), class: "btn waves-effect waves-light" do
      = t("global.show")
      %i.fa.fa-eye
    .btn.deep-orange.darken-4.waves-effect.waves-light.js-destroy-modal{data: {id: diet.id}}
      = t("global.delete")
      %i.fa.fa-trash

app/views/diets/index.haml
.row
  .container
    %h1
      = t("activerecord.diet.diets")

    - if @diets.present?
      = link_to t("activerecord.diet.new_diet"), new_diet_path, class: 'btn waves-effect waves-light js-new-diet'
      %table.striped.highlight.centered#diet-list
        %thead
          %tr
            %th
              = t("activerecord.diet.name")
            %th
              = t("activerecord.diet.kcal")
            %th
        %tbody
          - @diets.each do |diet|
            = render partial: 'diet_item', locals: {diet: diet}
    - else
      .center
        %h5
          = t("activerecord.diet.no_diets")
        = link_to t("activerecord.diet.new_diet"), new_diet_path, class: 'btn waves-effect waves-light js-new-diet'

#js-destroy-modal.modal.bottom-sheet
  .modal-content.center
    .btn.deep-orange.darken-4.waves-effect.waves-light.js-destroy-diet{data: {id: ''}}
      = t("global.delete")
      %i.fa.fa-trash
  .modal-footer
    .btn.btn-flat.modal-close
      = t("global.close")
      %i.fa.fa-times

#js-new-modal.modal

app/views/diets/new.haml
-#.row
-#  .container
-#    %h1
-#      = t("activerecord.diet.new_diet")
-#
-#    = form_for @new_diet, format: :json, html: {id: "js-new-diet"} do |f|
-#      .input-field
-#        = f.label :name, t("activerecord.diet.name")
-#        = f.text_field :name, autofocus: true
-#        .error.red-text
-#      .input-field
-#        = f.label :kcal, t("activerecord.diet.kcal")
-#        = f.number_field :kcal
-#        .error.red-text
-#      .actions.input-field
-#        = f.button t("activerecord.diet.create_diet"), class: 'btn waves-effect waves-light', type: :submit
-#= render partial: "shared/preloader"

= form_for @new_diet, format: :json, html: {id: "js-new-diet"} do |f|
  .modal-content
    %i.fa.fa-times.modal-close.right
    .input-field
      = f.label :name, t("activerecord.diet.name")
      = f.text_field :name, autofocus: true
      .error.red-text
    .input-field
      = f.label :kcal, t("activerecord.diet.kcal")
      = f.number_field :kcal
      .error.red-text
  .modal-footer
    .actions.input-field
      = f.button t("activerecord.diet.create_diet"), class: 'btn waves-effect waves-light', type: :submit
    -#= render partial: "shared/preloader"

app/views/diets/show.haml
.row
  .container
    .col.s6.center
      .row
        %h6
          = t("activerecord.diet.name")
      .row
        %h5
          = @diet.name
    .col.s6.center
      .row
        %h6
          = t("activerecord.diet.kcal")
      .row
        %h5
          = @diet.kcal
    #diet-id{data: {id: "#{@diet.id}"}}

    - if @day_diets.present?
      .row
        = link_to t("activerecord.day_diet.new"), new_day_diet_path, class: 'btn waves-effect waves-light js-new-day-diet'
      .row#day-diet-list
        - @day_diets.each do |day_diet|
          = render partial: 'day_diets/day_diet_item', locals: {day_diet: day_diet}
    - else
      .center
        %h5
          = t("activerecord.day_diet.no_day_diets")
        = link_to t("activerecord.day_diet.new"), new_day_diet_path, class: 'btn waves-effect waves-light js-new-day-diet'


#js-destroy-modal.modal.bottom-sheet
  .modal-content.center
    .btn.deep-orange.darken-4.waves-effect.waves-light.js-destroy-day-diet{data: {id: ''}}
      = t("global.delete")
      %i.fa.fa-trash
  .modal-footer
    .btn.btn-flat.modal-close
      = t("global.close")
      %i.fa.fa-times

#js-new-modal.modal