config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      unlocks: 'users/unlocks',
      passwords: 'user/passwords'
  }

  resources :products do
    collection do
      get :search
      post :search_for_dish
    end
  end

  get "/calculators" => "home#calculators", as: :calculators
  get "/informacje" => "home#info", as: :info
  post "/bmi" => "home#bmi", as: :bmi

  resources :day_diets
  resources :diets
  resources :dishes
  resources :ingredients do
    member do
      get :info
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :ingredients

  scope :name_search, -> (name) {where("name LIKE '%#{name}%'")}
  scope :protein_gte, -> (val) {where("protein >= ?",val)}
  scope :fat_gte, -> (val) {where("fat >= ?",val)}
  scope :carbohydrates_gte, -> (val) {where("carbohydrates >= ?",val)}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    query = params[:query]
    if query.present?
      products = Product.where(nil)
      query.each do |k,v|
        products = products.public_send(k,v) if v.present?
      end
    else
      products = Product.order("RANDOM()").limit(30)
    end

    render json: products
  end

  def search_for_dish
    if params[:query].present?
      @products = Product.name_search(params[:query])
    else
      @products = Product.all
    end

    render json: {products: render_to_string(partial: "products/group_product_items")}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.fetch(:product, {})
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.haml
= form_for(product) do |f|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li
            = message
  .actions
    = f.submit

app/views/products/_group_product_items.haml
#product-list
  - @products.in_groups_of(3,false) do |row_product|
    .row.row-product
      - for product in row_product
        = render partial: 'products/product_item', locals: {product: product}

app/views/products/_product_item.haml
.product.col.s4{id: "product#{product.id}", data: {f: product.fat, c: product.carbohydrates, p: product.protein, id: product.id}}
  .card.horizontal.hoverable
    .card-stacked
      .card-content
        .center
          = product.name

app/views/products/_product_item_onlist.haml
.product-onlist.col.s4{id: "ingredient#{ingredient.id}", data: {id: ingredient.id}}
  .card.horizontal.hoverable
    .card-stacked
      .card-content
        .center
          = ingredient.product.name

app/views/products/edit.haml
%h1 Editing Product
= render partial: 'form', locals: {product: @product}
= link_to 'Show', @product
|
= link_to 'Back', products_path

app/views/products/index.haml
= react_component 'Products'

app/views/products/new.haml
%h1 New Product
= render partial: 'form', locals: {product: @product}
= link_to 'Back', products_path

app/views/products/show.haml
%p#notice= notice
= link_to 'Edit', edit_product_path(@product)
|
= link_to 'Back', products_path