config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      unlocks: 'users/unlocks',
      passwords: 'user/passwords'
  }

  resources :products do
    collection do
      get :search
      post :search_for_dish
    end
  end

  get "/calculators" => "home#calculators", as: :calculators
  get "/informacje" => "home#info", as: :info
  post "/bmi" => "home#bmi", as: :bmi

  resources :day_diets
  resources :diets
  resources :dishes
  resources :ingredients do
    member do
      get :info
    end
  end

end

app/views/layouts/_footer.haml
%footer.page-footer.light-green
  .container
    .row
      .col.l6.s12
        %h5.white-text Zmień swoją sylwetkę!

      .col.l4.offset-l2.s12
        %h5.white-text Linki
        %ul
          %li
            = link_to "Produkty", products_path, class: "grey-text text-lighten-3"
          %li
            = link_to "BMI", calculators_path, class: "grey-text text-lighten-3"
          %li
            = link_to "Informacje", info_path, class: "grey-text text-lighten-3"
          - if current_user
            %li
              = link_to t('devise.diets'), diets_path, class: "grey-text text-lighten-3"
            %li
              = link_to t('devise.edit_profile'), edit_user_registration_path, class: "grey-text text-lighten-3"
  .footer-copyright
    .container
      MealtWeight © 2017 Daniel Niedziałkowski

app/views/layouts/_header.haml
%header
  .navbar-fixed
    %nav.light-green
      .nav-wrapper.container
        = link_to "MealtWeight", root_path, class: 'brand-logo hide-on-med-and-down'
        %ul.right
          %li
            = link_to "Produkty", products_path
          %li
            = link_to "BMI", calculators_path
          %li
            = link_to "Informacje", info_path
          %li
            - if current_user
              %a.slide-menu{"data-activates" => "slide-menu"} Profil
            - else
              = link_to t('devise.log_in'), new_user_session_path
  - if current_user
    %ul#slide-menu.side-nav
      %li
        .userView.light-green
          -#.background
            -#%img{:src => "images/office.jpg"}/
          -#%a{:href => "#!user"}
            -#%img.circle{:src => "images/yuna.jpg"}/
          %span.white-text.email
            = current_user.email
      %li
        = link_to t('devise.diets'), diets_path
      %li
        = link_to t('devise.edit_profile'), edit_user_registration_path
      %li
        .divider
      %li
        = link_to t('devise.log_out'), destroy_user_session_path, :method => :delete

app/views/layouts/application.haml
!!!
%html
  %head
    %title Meal
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'#, 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'#, 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/header'
    %main
      = yield
    = render partial: 'layouts/footer'

    - if alert
      #permission_error_handle.hide{data: {message: t('activerecord.authorization_error')}}